-- USERS TABLE
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- PUBLISHERS TABLE
CREATE TABLE publishers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE,
    address VARCHAR(200),
    phone_number VARCHAR(20),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- AUTHORS TABLE
CREATE TABLE authors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE,
    birth_date DATE,
    biography VARCHAR(500),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- BOOKS TABLE
CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    isbn VARCHAR(17) NOT NULL UNIQUE,
    description VARCHAR(1000),
    publication_date DATE,
    page_count INT,
    price DECIMAL(10, 2),
    status VARCHAR(20) NOT NULL,
    cover_image_url VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    author_id BIGINT NOT NULL,
    publisher_id BIGINT, -- This is NULL by default in Postgres, no need to specify NULL
    CONSTRAINT fk_books_author FOREIGN KEY (author_id) REFERENCES authors(id) ON DELETE RESTRICT,
    CONSTRAINT fk_books_publisher FOREIGN KEY (publisher_id) REFERENCES publishers(id) ON DELETE SET NULL
);

-- BORROW_RECORD TABLE
CREATE TABLE borrow_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    book_id BIGINT,
    borrow_date DATE,
    return_date DATE,
    status VARCHAR(20),
    CONSTRAINT fk_borrow_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_borrow_book FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
);